name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.13-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install .[dev]

      - name: Lint with pylint
        run: run pylint lawnmower tests

      - name: Type check with mypy
        run: run mypy lawnmower

      - name: Run tests
        run: run pytest --cov --cov-report=term-missing
